# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73dcf4e53bb00565966a22bf8339b9ae756c114fe949b43f6ae24771d69d4c3be96640bcae58202d36b5bf90d1a283667adac9783e12208590b79637d7dee593

test:
  secret_key_base: c802d997a135c52a53738bdd1350fbb65516e592981a69a68ff42d48c6e2ac91efa67fb5e651894d0447c6debfda85266ec1b4ce3ac323373d5403c72028ab86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
